Neos:
  Neos:
    modules:
      management:
        submodules:
          workspaces:
            label: 'Neos.Neos:Modules:workspaces.label'
            controller: 'Neos\Workspace\Ui\Controller\WorkspacesController'
            description: 'Neos.Neos:Modules:workspaces.description'
            icon: fas fa-th-large
            mainStylesheet: 'Lite'
            additionalResources:
              javaScripts:
                Shel.Neos.WorkspaceModule: 'resource://Neos.Workspace.Ui/Public/Assets/main.js'
